# 01_add_groups.yaml
#
# This file will create user identity groups in the internal ISE identity store.
# You should not need to modify this file as it will dynamically read all of the groups
# from groupsandusers.yaml.

- hosts: ise_servers
# Read in some variables
  vars_files:
    - credentials.yaml  # read the ISE host and admin credentials
    - groupsandusers.yaml  # read in the list of groups and users
  gather_facts: false
  tasks:
    - name: Create groups from the group list read above
      cisco.ise.identity_group:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: present
        name: "{{ item.name }}"  # group name from the group list
        description: "{{ item.desc }}"  # group description from the group list
        parent: "NAC Group:NAC:IdentityGroups:User Identity Groups"
      loop: "{{ usergroups }}"  # the group list variable
      register: identity_group  # register the output to a variable

# Uncomment everything below this line if you want to see more information about the results.
# You can move this block under any task to get more info.

    #   register: result

    # - name: Print Authorization profile
    #   ansible.builtin.debug:
    #     var: result
